sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
language:
- java
script:
- ./gradlew clean compileJava
- ./gradlew :lb-hazelcast-common:uploadArchives
- ./gradlew :lb-hazelcast-config:uploadArchives
- ./gradlew :lb-hazelcast-config-json:uploadArchives
- ./gradlew :lb-hazelcast-config-yaml:uploadArchives
- ./gradlew :lb-hazelcast-serialization:uploadArchives
- ./gradlew :lb-hazelcast-serialization-fst:uploadArchives
- ./gradlew :lb-hazelcast-serialization-json:uploadArchives
- ./gradlew :lb-hazelcast-serialization-kryo:uploadArchives

jdk:
- oraclejdk8

env:
  global:    
  - CI_TRAVIS=true
  - secure: V29UeliEnGcDBsExqQsvDkij7nZP6vUsE9ABunZSohG07uMLOMQlG7LXeCtqZJ3UP5qfniYxOudvlpdLiEobtCubX4Y1D9057tVwLtW6UuQFU4lSqN9pIEA7roKAyfH6JWOEw6lWlQQtq483VQSg9kfg19mO+Y4ZjOstjIhcqck=
  - secure: SRh2oopvhdtto2112Lqb1LzlmdaRjY3KcKq0sy3Jyin1nyd1cXnDd9y0mb+zVvCrvzc3mUwxRfV1dsok+wtLdYdoB+YsENfMFB+T/T2qlqxut2hLXrkVnxst2refSsnlV6jS4GJQ0VLZiJq25PqigEFkPMRAjnHGoEMXvptinSw=
